### Get all the books in the database
GET http://localhost:3000/books


### Get single book from the database
GET http://localhost:3000/books/674565e8577e077c5e774755


### Insert a new book to the database
POST http://localhost:3000/books
Content-Type: application/json


{
  "title":"The Goldfinch",
  "authorId":"1",
  "isbn":"9780316055437",
  "edition":"Paperback",
  "pubDate":"2013-10-22",
  "genre":"Fiction",
  "cover":"https://m.media-amazon.com/images/I/71ud9Tcj5YL.jpg"
}


### update a book information
PUT http://localhost:3000/books/674565e8577e077c5e774755
Content-Type: application/json

{
  "cover": "https://m.media-amazon.com/images/I/91-LL7OnDCL._AC_UF1000,1000_QL80_.jpg"
}
