### Get all the books in the database
GET http://localhost:3000/books


### Get single book from the database
GET http://localhost:3000/books/674e9027d8a0e1389c0390e5


### Insert a new book to the database
POST http://localhost:3000/books
Content-Type: application/json

{
  "title": "Harry Potter and the Goblet of Fire",
  "authorId": "4",
  "isbn": "9780439139601",
  "edition": "Paperback",
  "pubDate": "2000-07-08",
  "genre": "Fantasy",
  "cover": "https://m.media-amazon.com/images/I/91-LL7OnDCL._AC_UF1000,1000_QL80_.jpg"
}


### update a book information
PUT http://localhost:3000/books/674e9027d8a0e1389c0390e5
Content-Type: application/json

{
  "edition": "Paperback"
}


### Delete book item
DELETE http://localhost:3000/books/674e9eb19a22fb638db4a73c